[package]
name = "trie-db-test"
version = "0.31.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Tests for trie-db crate"
repository = "https://github.com/paritytech/trie"
license = "Apache-2.0"
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
trie-db = { path = "..", version = "0.31.0"}
hash-db = { path = "../../hash-db", version = "0.16.0"}
memory-db = { path = "../../memory-db", version = "0.34.0" }
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
trie-standardmap = { path = "../../test-support/trie-standardmap", version = "0.16.0" }
reference-trie = { path = "../../test-support/reference-trie", version = "0.29.0" }
hex-literal = "0.4"
criterion = "0.5.1"
env_logger = { version = "0.10", default-features = false }
log = "0.4"
twox-hash = {version="1.6.3",  features = ["digest_0_10"]}
blake2b_simd = "1.0.4"
hash256-std-hasher = { path = "../../hash256-std-hasher", version = "0.15.2" }
byteorder = { version = "1.3.2", default-features = false }
digest = { version = "0.10.3", default-features = false }
env = "1.0.1"
rocksdb = "0.24.0"
tempfile = "3"  
once_cell = "1.19"

[dev-dependencies]
array-bytes = "6.0.0"
keccak-hasher = { path = "../../test-support/keccak-hasher" }